services:
  # Backend Service (Node.js API)
  - type: web
    name: dediwarn-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://dediwarn-frontend.onrender.com
      - key: OPENWEATHER_API_KEY
        value: demo_key

  # Frontend Service (Static Site)
  - type: web
    name: dediwarn-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://dediwarn-backend.onrender.com
