services:
  # Backend Service (Node.js API)
  - type: web
    name: dediwarn-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://dediwarn-frontend.onrender.com
      - key: OPENWEATHER_API_KEY
        value: demo_key
      - key: FRONTEND_URL
        value: https://dediwarn-frontend.onrender.com

  # Frontend Service (Static Site)
  - type: web
    name: dediwarn-frontend
    env: static
    region: oregon
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://dediwarn-backend.onrender.com
      - key: VITE_WEBSOCKET_URL
        value: wss://dediwarn-backend.onrender.com
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
